-- Data model v2, P2 expand (SA2-302): currency becomes the asset table, plus
-- asset_rate, ledger_category, ledger_line and user_setting. Nothing reads or
-- writes them yet; the services come in T11 and the cutover in T12.
--
-- Generated by db:generate, then edited by hand:
-- - Every CREATE is IF NOT EXISTS because a migration file is not one
--   transaction in production (.claude/rules/db-migrations.md). The new tables
--   reference only parents that already exist with their UNIQUE (id, user_id)
--   indexes (currency, entry, play_session, play_event), so they come first.
-- - ADD COLUMN cannot be guarded, so the three currency columns come last,
--   right before the index that needs `kind`.
-- - Drizzle can declare a CHECK only on the table, and adding one makes
--   db:generate rebuild currency, a parent whose DROP would cascade into its
--   children. So the CHECKs on currency.kind and currency.decimals are
--   column constraints of the ADD COLUMN, outside the Drizzle snapshot. The
--   values come from packages/db/src/constants/asset.ts. SQLite checks them
--   against the existing rows, which all take the defaults.
CREATE TABLE IF NOT EXISTS `asset_rate` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`base_asset_id` text NOT NULL,
	`quote_asset_id` text NOT NULL,
	`rate_num` integer NOT NULL,
	`rate_den` integer NOT NULL,
	`effective_from` integer NOT NULL,
	`memo` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`base_asset_id`,`user_id`) REFERENCES `currency`(`id`,`user_id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`quote_asset_id`,`user_id`) REFERENCES `currency`(`id`,`user_id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "asset_rate_distinct_assets_check" CHECK("asset_rate"."base_asset_id" <> "asset_rate"."quote_asset_id"),
	CONSTRAINT "asset_rate_rate_num_check" CHECK("asset_rate"."rate_num" BETWEEN 1 AND 1000000000000),
	CONSTRAINT "asset_rate_rate_den_check" CHECK("asset_rate"."rate_den" BETWEEN 1 AND 1000000000000)
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `asset_rate_pair_effective_from_unique` ON `asset_rate` (`user_id`,`base_asset_id`,`quote_asset_id`,`effective_from`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `ledger_category` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`archived_at` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `ledger_category_id_user_id_unique` ON `ledger_category` (`id`,`user_id`);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `ledger_category_user_name_unique` ON `ledger_category` (`user_id`,lower("name"));--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `ledger_line` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`asset_id` text NOT NULL,
	`quantity` integer NOT NULL,
	`role` text NOT NULL,
	`effect` text NOT NULL,
	`entry_id` text,
	`play_session_id` text,
	`source_event_id` text,
	`category_id` text,
	`transfer_id` text,
	`occurred_at` integer NOT NULL,
	`memo` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`asset_id`,`user_id`) REFERENCES `currency`(`id`,`user_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`entry_id`,`user_id`) REFERENCES `entry`(`id`,`user_id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`play_session_id`,`entry_id`,`user_id`) REFERENCES `play_session`(`id`,`entry_id`,`user_id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`source_event_id`,`user_id`) REFERENCES `play_event`(`id`,`user_id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`category_id`,`user_id`) REFERENCES `ledger_category`(`id`,`user_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ledger_line_role_check" CHECK("ledger_line"."role" IN ('buy_in', 'reentry', 'fee', 'chip_purchase', 'addon', 'chip_remove', 'cash_out', 'prize', 'bounty', 'adjustment', 'exchange')),
	CONSTRAINT "ledger_line_effect_check" CHECK("ledger_line"."effect" IN ('real', 'virtual')),
	CONSTRAINT "ledger_line_quantity_check" CHECK("ledger_line"."quantity" <> 0 AND abs("ledger_line"."quantity") <= 1000000000000),
	CONSTRAINT "ledger_line_role_sign_check" CHECK(("ledger_line"."role" IN ('buy_in', 'reentry', 'fee', 'chip_purchase', 'addon') AND "ledger_line"."quantity" < 0) OR ("ledger_line"."role" IN ('chip_remove', 'cash_out', 'prize', 'bounty') AND "ledger_line"."quantity" > 0) OR "ledger_line"."role" IN ('adjustment', 'exchange')),
	CONSTRAINT "ledger_line_role_entry_check" CHECK(("ledger_line"."role" IN ('adjustment', 'exchange') AND "ledger_line"."entry_id" IS NULL AND "ledger_line"."effect" = 'real') OR (NOT ("ledger_line"."role" IN ('adjustment', 'exchange')) AND "ledger_line"."entry_id" IS NOT NULL)),
	CONSTRAINT "ledger_line_exchange_transfer_check" CHECK("ledger_line"."role" <> 'exchange' OR "ledger_line"."transfer_id" IS NOT NULL),
	CONSTRAINT "ledger_line_play_session_entry_check" CHECK("ledger_line"."play_session_id" IS NULL OR "ledger_line"."entry_id" IS NOT NULL)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `ledger_line_user_entry_idx` ON `ledger_line` (`user_id`,`entry_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `ledger_line_user_asset_occurred_at_idx` ON `ledger_line` (`user_id`,`asset_id`,`occurred_at`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `ledger_line_source_event_idx` ON `ledger_line` (`source_event_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `ledger_line_play_session_idx` ON `ledger_line` (`play_session_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `ledger_line_transfer_idx` ON `ledger_line` (`transfer_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `user_setting` (
	`user_id` text PRIMARY KEY NOT NULL,
	`base_asset_id` text,
	`time_zone` text,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`base_asset_id`,`user_id`) REFERENCES `currency`(`id`,`user_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
ALTER TABLE `currency` ADD `kind` text DEFAULT 'currency' NOT NULL CONSTRAINT "currency_kind_check" CHECK("kind" IN ('currency', 'item'));--> statement-breakpoint
ALTER TABLE `currency` ADD `decimals` integer DEFAULT 0 NOT NULL CONSTRAINT "currency_decimals_check" CHECK("decimals" BETWEEN 0 AND 4);--> statement-breakpoint
ALTER TABLE `currency` ADD `archived_at` integer;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `currency_user_kind_idx` ON `currency` (`user_id`,`kind`);