/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ActiveSessionRouteImport } from './routes/active-session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as CurrenciesIndexRouteImport } from './routes/currencies/index'
import { Route as ActiveSessionIndexRouteImport } from './routes/active-session/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as CurrenciesCurrencyIdRouteImport } from './routes/currencies/$currencyId'
import { Route as ActiveSessionGameRouteImport } from './routes/active-session/game'
import { Route as ActiveSessionEventsRouteImport } from './routes/active-session/events'
import { Route as LiveSessionsSessionTypeSessionIdEventsRouteImport } from './routes/live-sessions/$sessionType/$sessionId/events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveSessionRoute = ActiveSessionRouteImport.update({
  id: '/active-session',
  path: '/active-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesIndexRoute = CurrenciesIndexRouteImport.update({
  id: '/currencies/',
  path: '/currencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveSessionIndexRoute = ActiveSessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActiveSessionRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesCurrencyIdRoute = CurrenciesCurrencyIdRouteImport.update({
  id: '/currencies/$currencyId',
  path: '/currencies/$currencyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveSessionGameRoute = ActiveSessionGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => ActiveSessionRoute,
} as any)
const ActiveSessionEventsRoute = ActiveSessionEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ActiveSessionRoute,
} as any)
const LiveSessionsSessionTypeSessionIdEventsRoute =
  LiveSessionsSessionTypeSessionIdEventsRouteImport.update({
    id: '/live-sessions/$sessionType/$sessionId/events',
    path: '/live-sessions/$sessionType/$sessionId/events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-session': typeof ActiveSessionRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/active-session/events': typeof ActiveSessionEventsRoute
  '/active-session/game': typeof ActiveSessionGameRoute
  '/currencies/$currencyId': typeof CurrenciesCurrencyIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/active-session/': typeof ActiveSessionIndexRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/live-sessions/$sessionType/$sessionId/events': typeof LiveSessionsSessionTypeSessionIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statistics': typeof StatisticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/active-session/events': typeof ActiveSessionEventsRoute
  '/active-session/game': typeof ActiveSessionGameRoute
  '/currencies/$currencyId': typeof CurrenciesCurrencyIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/active-session': typeof ActiveSessionIndexRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/live-sessions/$sessionType/$sessionId/events': typeof LiveSessionsSessionTypeSessionIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-session': typeof ActiveSessionRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/active-session/events': typeof ActiveSessionEventsRoute
  '/active-session/game': typeof ActiveSessionGameRoute
  '/currencies/$currencyId': typeof CurrenciesCurrencyIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/active-session/': typeof ActiveSessionIndexRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/live-sessions/$sessionType/$sessionId/events': typeof LiveSessionsSessionTypeSessionIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-session'
    | '/statistics'
    | '/login'
    | '/settings'
    | '/active-session/events'
    | '/active-session/game'
    | '/currencies/$currencyId'
    | '/players/$playerId'
    | '/rooms/$roomId'
    | '/sessions/$sessionId'
    | '/active-session/'
    | '/currencies/'
    | '/players/'
    | '/rooms/'
    | '/sessions/'
    | '/live-sessions/$sessionType/$sessionId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/statistics'
    | '/login'
    | '/settings'
    | '/active-session/events'
    | '/active-session/game'
    | '/currencies/$currencyId'
    | '/players/$playerId'
    | '/rooms/$roomId'
    | '/sessions/$sessionId'
    | '/active-session'
    | '/currencies'
    | '/players'
    | '/rooms'
    | '/sessions'
    | '/live-sessions/$sessionType/$sessionId/events'
  id:
    | '__root__'
    | '/'
    | '/active-session'
    | '/statistics'
    | '/login'
    | '/settings'
    | '/active-session/events'
    | '/active-session/game'
    | '/currencies/$currencyId'
    | '/players/$playerId'
    | '/rooms/$roomId'
    | '/sessions/$sessionId'
    | '/active-session/'
    | '/currencies/'
    | '/players/'
    | '/rooms/'
    | '/sessions/'
    | '/live-sessions/$sessionType/$sessionId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveSessionRoute: typeof ActiveSessionRouteWithChildren
  StatisticsRoute: typeof StatisticsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CurrenciesCurrencyIdRoute: typeof CurrenciesCurrencyIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  CurrenciesIndexRoute: typeof CurrenciesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  LiveSessionsSessionTypeSessionIdEventsRoute: typeof LiveSessionsSessionTypeSessionIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-session': {
      id: '/active-session'
      path: '/active-session'
      fullPath: '/active-session'
      preLoaderRoute: typeof ActiveSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/': {
      id: '/currencies/'
      path: '/currencies'
      fullPath: '/currencies/'
      preLoaderRoute: typeof CurrenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-session/': {
      id: '/active-session/'
      path: '/'
      fullPath: '/active-session/'
      preLoaderRoute: typeof ActiveSessionIndexRouteImport
      parentRoute: typeof ActiveSessionRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/$currencyId': {
      id: '/currencies/$currencyId'
      path: '/currencies/$currencyId'
      fullPath: '/currencies/$currencyId'
      preLoaderRoute: typeof CurrenciesCurrencyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-session/game': {
      id: '/active-session/game'
      path: '/game'
      fullPath: '/active-session/game'
      preLoaderRoute: typeof ActiveSessionGameRouteImport
      parentRoute: typeof ActiveSessionRoute
    }
    '/active-session/events': {
      id: '/active-session/events'
      path: '/events'
      fullPath: '/active-session/events'
      preLoaderRoute: typeof ActiveSessionEventsRouteImport
      parentRoute: typeof ActiveSessionRoute
    }
    '/live-sessions/$sessionType/$sessionId/events': {
      id: '/live-sessions/$sessionType/$sessionId/events'
      path: '/live-sessions/$sessionType/$sessionId/events'
      fullPath: '/live-sessions/$sessionType/$sessionId/events'
      preLoaderRoute: typeof LiveSessionsSessionTypeSessionIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActiveSessionRouteChildren {
  ActiveSessionEventsRoute: typeof ActiveSessionEventsRoute
  ActiveSessionGameRoute: typeof ActiveSessionGameRoute
  ActiveSessionIndexRoute: typeof ActiveSessionIndexRoute
}

const ActiveSessionRouteChildren: ActiveSessionRouteChildren = {
  ActiveSessionEventsRoute: ActiveSessionEventsRoute,
  ActiveSessionGameRoute: ActiveSessionGameRoute,
  ActiveSessionIndexRoute: ActiveSessionIndexRoute,
}

const ActiveSessionRouteWithChildren = ActiveSessionRoute._addFileChildren(
  ActiveSessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveSessionRoute: ActiveSessionRouteWithChildren,
  StatisticsRoute: StatisticsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CurrenciesCurrencyIdRoute: CurrenciesCurrencyIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  CurrenciesIndexRoute: CurrenciesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  LiveSessionsSessionTypeSessionIdEventsRoute:
    LiveSessionsSessionTypeSessionIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
