/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as LiveSessionsIndexRouteImport } from './routes/live-sessions/index'
import { Route as CurrenciesIndexRouteImport } from './routes/currencies/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as LiveSessionsCashGameSessionIdRouteImport } from './routes/live-sessions/cash-game/$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSessionsIndexRoute = LiveSessionsIndexRouteImport.update({
  id: '/live-sessions/',
  path: '/live-sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesIndexRoute = CurrenciesIndexRouteImport.update({
  id: '/currencies/',
  path: '/currencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSessionsCashGameSessionIdRoute =
  LiveSessionsCashGameSessionIdRouteImport.update({
    id: '/live-sessions/cash-game/$sessionId',
    path: '/live-sessions/cash-game/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/live-sessions/': typeof LiveSessionsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/live-sessions/cash-game/$sessionId': typeof LiveSessionsCashGameSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/live-sessions': typeof LiveSessionsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/live-sessions/cash-game/$sessionId': typeof LiveSessionsCashGameSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/live-sessions/': typeof LiveSessionsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/live-sessions/cash-game/$sessionId': typeof LiveSessionsCashGameSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/settings'
    | '/stores/$storeId'
    | '/currencies/'
    | '/live-sessions/'
    | '/players/'
    | '/sessions/'
    | '/stores/'
    | '/live-sessions/cash-game/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/settings'
    | '/stores/$storeId'
    | '/currencies'
    | '/live-sessions'
    | '/players'
    | '/sessions'
    | '/stores'
    | '/live-sessions/cash-game/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/settings'
    | '/stores/$storeId'
    | '/currencies/'
    | '/live-sessions/'
    | '/players/'
    | '/sessions/'
    | '/stores/'
    | '/live-sessions/cash-game/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  CurrenciesIndexRoute: typeof CurrenciesIndexRoute
  LiveSessionsIndexRoute: typeof LiveSessionsIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  LiveSessionsCashGameSessionIdRoute: typeof LiveSessionsCashGameSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-sessions/': {
      id: '/live-sessions/'
      path: '/live-sessions'
      fullPath: '/live-sessions/'
      preLoaderRoute: typeof LiveSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/': {
      id: '/currencies/'
      path: '/currencies'
      fullPath: '/currencies/'
      preLoaderRoute: typeof CurrenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-sessions/cash-game/$sessionId': {
      id: '/live-sessions/cash-game/$sessionId'
      path: '/live-sessions/cash-game/$sessionId'
      fullPath: '/live-sessions/cash-game/$sessionId'
      preLoaderRoute: typeof LiveSessionsCashGameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  CurrenciesIndexRoute: CurrenciesIndexRoute,
  LiveSessionsIndexRoute: LiveSessionsIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  LiveSessionsCashGameSessionIdRoute: LiveSessionsCashGameSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
